FROM linuxserver/openssh-server:latest as builder

RUN apk add --no-cache build-base git linux-pam-dev

RUN git clone https://github.com/pbrezina/pam-test.git pam-test \
    && cd pam-test && make


##########################################################

FROM linuxserver/openssh-server:latest

COPY --from=builder /pam-test/pam_test /bin/

COPY ./target_pam_setup.sh .
RUN sudo ./target_pam_setup.sh
